### PR TITLE
feat: add elastic search to eval

### PR DESCRIPTION
**Pull request by mirkobronzi**
## Description

added Elastic Search for evaluation.

### CODE REVIEW

**Comment by lp-noel** [comment]
To test this model we first need to build it right before calling the evaluation code right?

**Comment by mirkobronzi** [comment]
> To test this model we first need to build it right before calling the evaluation code right?

The elastic search one? No, the index will be built on the fly (in the `collect_asnwer` method).
But you need to have an elastic search server running (on localhost:9200)..

**Comment by lp-noel** [comment]
> > To test this model we first need to build it right before calling the evaluation code right?
> 
> The elastic search one? No, the index will be built on the fly (in the `collect_asnwer` method).
> But you need to have an elastic search server running (on localhost:9200)..

Ok can you please add doc about how to do this in the README?

**Comment by mirkobronzi** [comment]
> > > To test this model we first need to build it right before calling the evaluation code right?
> > 
> > 
> > The elastic search one? No, the index will be built on the fly (in the `collect_asnwer` method).
> > But you need to have an elastic search server running (on localhost:9200)..
> 
> Ok can you please add doc about how to do this in the README?

sure - just done.

**Pull request merged**
